<?php

Dict::Add('EN US', 'English', 'English', array(
	
		//Bug class
        "Class:Bug" => "Bug",
        "Class:Bug+" => "Defect, enhencement or new feature for a product",
        "Class:Bug/Attribute:summary" => "Summary",
        "Class:Bug/Attribute:summary+" => "A one sentence summery of the problem",
        "Class:Bug/Attribute:reference" => "Reference",
        "Class:Bug/Attribute:reference+" => "Bug tracking reference for this bug",
        "Class:Bug/Attribute:status" => "Status",
        "Class:Bug/Attribute:status+" => "Status for this bug",
        "Class:Product" => "Product",
        "Class:Product+" => "An IT product",
        "Class:Component" => "Component",
        "Class:Component+" => "A product's component",
        "Class:Component/Attribute:product_id" => "Product id",
        "Class:Component/Attribute:product_id+" => "",
        "Class:Product/Attribute:status" => "Status",
        "Class:Product/Attribute:status+" => "",
        "Class:Bug/Attribute:status/Value:new" => "New",
        "Class:Bug/Attribute:status/Value:confirmed" => "Confirmed",
        "Class:Bug/Attribute:status/Value:inprogress" => "In progress",
        "Class:Bug/Attribute:status/Value:resolved" => "Resolved",
        "Class:Bug/Attribute:status/Value:unconfirmed" => "Unconfirmed",
        "Class:Bug/Attribute:status/Value:closed" => "Closed",
        "Class:Bug/Attribute:product_id" => "Product id",
        "Class:Bug/Attribute:product_id+" => "Product on which this bug happends",
        "Class:Bug/Attribute:component_id" => "Component",
        "Class:Bug/Attribute:component_id+" => "Product's component on which this bug happens",
        "Class:Bug/Attribute:version" => "Version",
        "Class:Bug/Attribute:version+" => "Version(s) on which this bug happens",
        "Class:Bug/Attribute:priority" => "Priority",
        "Class:Bug/Attribute:priority+" => "Priority for this bug",
        "Class:Bug/Attribute:severity" => "Severity",
        "Class:Bug/Attribute:severity+" => "Severity for this bug",
        "Class:Bug/Attribute:priority/Value:p1" => "P1 Critical",
        "Class:Bug/Attribute:priority/Value:p2" => "P2 High",
        "Class:Bug/Attribute:priority/Value:p3" => "P3 Medium ",
        "Class:Bug/Attribute:priority/Value:p4" => "P4 Low",
        "Class:Bug/Attribute:severity/Value:s1" => "S1 Critical",
        "Class:Bug/Attribute:severity/Value:s2" => "S2 Major",
        "Class:Bug/Attribute:severity/Value:s3" => "S3 Moderate",
        "Class:Bug/Attribute:severity/Value:s4" => "S4 Low",
        "Class:Bug/Attribute:target_version" => "Target version",
        "Class:Bug/Attribute:target_version+" => "Target version(s) in which the bug will be fixed",
        "Class:Bug/Attribute:team_id" => "Team id",
        "Class:Bug/Attribute:team_id+" => "",
        "Class:Bug/Attribute:assigned_to" => "Assigned to",
        "Class:Bug/Attribute:assigned_to+" => "Person assigned to this bug",
        "Class:Bug/Attribute:description" => "Description",
        "Class:Bug/Attribute:description+" => "Bug's complete description",
        "Class:Bug/Attribute:domains" => "Domains",
        "Class:Bug/Attribute:domains+" => "",
        "Class:Bug/Attribute:parent_bug_id" => "Parent bug id",
        "Class:Bug/Attribute:parent_bug_id+" => "",
        "Class:Bug/Attribute:reported_by" => "Reported by",
        "Class:Bug/Attribute:reported_by+" => "",
        "Class:Bug/Attribute:bug_log" => "Bug log",
        "Class:Bug/Attribute:bug_log+" => "",
        "Class:Bug/Stimulus:acknowledge" => "Acknowledge",
        "Class:Bug/Stimulus:confirm" => "Confirm bug",
        "Class:Bug/Stimulus:start_working" => "Start working",
        "Class:Bug/Stimulus:stop_working" => "Stop working",
        "Class:Bug/Stimulus:resolve" => "Resolve",
        "Class:Bug/Stimulus:unconfirm" => "Unconfirm",
        "Class:Bug/Stimulus:reopen" => "Reopen",
        "Class:Bug/Stimulus:close" => "Close",
        "Class:Product/Attribute:name" => "Name",
        "Class:Product/Attribute:name+" => "",
        "Class:Product/Attribute:desription" => "Desription",
        "Class:Product/Attribute:desription+" => "",
        "Class:Component/Attribute:name" => "Name",
        "Class:Component/Attribute:name+" => "",
	    "Class:Component/Attribute:product_id" => "Product",
	    "Class:Component/Attribute:product_id+" => "",
    	"Class:Component/Attribute:description" => "Description",
        "Class:Component/Attribute:description+" => "",
        "Class:Bug/Attribute:creation_date" => "Created on",
        "Class:Bug/Attribute:creation_date+" => "",
        "Class:Bug/Attribute:modified_date" => "Last modified",
        "Class:Bug/Attribute:modified_date+" => "",
        "Class:Bug/Attribute:update_date" => "Update date",
        "Class:Bug/Attribute:update_date+" => "",
        "Class:Bug/Attribute:resolution_code" => "Resolution code",
        "Class:Bug/Attribute:resolution_code+"  => "",
        "Class:Bug/Attribute:resolution_code/Value:fixed" => "Fixed",
        "Class:Bug/Attribute:resolution_code/Value:duplicate" => "Duplicate",
        "Class:Bug/Attribute:resolution_code/Value:wontfix" => "Won\'t fix",
        "Class:Bug/Attribute:resolution_code/Value:notreproduced" => "Not reproduced",
        "Class:Bug/Attribute:keywords" => "Keywords",
        "Class:Bug/Attribute:milestone_id" => "Milestone id",
        "Class:Bug/Name"  => '%1$s%2$s',
		"Class:Bug/Warning:Duplicate"  => '%1$s is a potential duplicate.',

	    "Menu:Bug:Mgmt" => "Bug Management",
        "Menu:Bug:New" => "New bug",
        "Menu:Bug:Overview" => "Bug Overview",
        "Menu:Bug:List" => "Search for Bugs",
        "Menu:Bug:Shortcuts" => "Bugs",
        "Menu:Product:Shortcuts" => "Products",
        "Menu:Product:Overview" => "Products Overview",
        "Menu:Product:List" => "Search for Products",
        "Menu:Product:New" => "New product",
        "Menu:Milestone:New" => "New milestone",
        "Menu:Component:New" => "New component",
		
		"BugDetails" => "Details",
		"BugProductDetails" => "Product details",
		"BugMeasures" => "Measures",
		"BugResolution" => "Resolution",
		"BugHistory" => "History",
    
        // Class milestone
        "Class:Milestone" => "Milestone",
        "Class:Milestone+" => "",
        "Class:Milestone/Attribute:product_id" => "Product",
        "Class:Milestone/Attribute:product_id+" => "",
        "Class:Milestone/Attribute:version" => "Version",
        "Class:Milestone/Attribute:version+" => "",
        "Class:Milestone/Attribute:description" => "Description",
        "Class:Milestone/Attribute:description+" => "",
    
        // Class Product 
        "Class:Product/Attribute:status/Value:active" => "active",
        "Class:Product/Attribute:status/Value:active+" => "",
        "Class:Product/Attribute:status/Value:inactive" => "inactive",
        "Class:Product/Attribute:status/Value:inactive+" => "",
        "Class:Product/Attribute:version" => "Version",
        "Class:Product/Attribute:version+" => "",

));
